### PR TITLE
fix(frontend): redirect on 401 instead of showing error

### LINKED ISSUE #187: Fix handling of expired tokens

### PR DESCRIPTION
**Pull request by fkm-adfinis**
This also includes some other improvements related to the session
handling. The main fix is to check for UnauthorizedError in a new
error action of the -authenticated route.

```js
@action error(error, transition) {
  if (error instanceof UnauthorizedError) {
    this.transitionTo("account.login");
    return false;
  }

  return true;
}
```

Fixes #187

### CODE REVIEW

File: frontend/app/ui/error/route.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import Route from "@ember/routing/route";
+import config from "customer-center/config/environment";
+
+export default class ErrorRoute extends Route {
+  setupController(controller, error) {
+    // Don't show internals in production.
+    controller.showStack = config.environment !== "production";
```
Comment (anehx) [inline frontend/app/ui/error/route.js:7]: Make this a getter in the controller - makes it easier to read

File: frontend/app/routes/-authenticated.js [hunk 2]
```diff
@@ -7,4 +9,13 @@ export default class AuthenticatedRoute extends BaseRoute {
...
   }
+
+  @action error(error, transition) {
+    if (error instanceof UnauthorizedError) {
+      this.transitionTo("account.login");
+      return false;
+    }
+
+    return true;
+  }
```
Comment (anehx) [inline frontend/app/routes/-authenticated.js:20]: Why aren't you using the example approach in the adapter? If you do a patch in an action this won't do anything. It will only work for model hooks.

File: frontend/app/ui/account/password-confirm/route.js [hunk 3]
```diff
@@ -1,6 +1,13 @@
 import Route from "@ember/routing/route";
+import { inject as service } from "@ember/service";
 
 export default class AccountPasswordConfirmRoute extends Route {
+  @service session;
+
+  beforeModel(transition) {
+    this.session.prohibitAuthentication("index");
+  }
```
Comment (anehx) [inline frontend/app/ui/account/password-confirm/route.js:9]: Same here

File: frontend/app/ui/account/login/route.js [hunk 4]
```diff
@@ -1,6 +1,13 @@
+import { inject as service } from "@ember/service";
 import BaseRoute from "customer-center/routes/-base";
 
 export default class AccountLoginRoute extends BaseRoute {
+  @service session;
+
+  beforeModel(transition) {
+    this.session.prohibitAuthentication("index");
+  }
```
Comment (anehx) [inline frontend/app/ui/account/login/route.js:9]: Shouldn't this route just extend the authenticated base route?

File: frontend/app/ui/error/route.js (hunk 1 above)
Comment (fkm-adfinis) [reply frontend/app/ui/error/route.js:7]: Ok

File: frontend/app/ui/account/login/route.js (hunk 4 above)
Comment (fkm-adfinis) [reply frontend/app/ui/account/login/route.js:9]: This route must not require authentication. Otherwise, the user cannot log in.

File: frontend/app/routes/-authenticated.js (hunk 2 above)
Comment (fkm-adfinis) [reply frontend/app/routes/-authenticated.js:20]: Just invalidating the session lead to the same result as requireAuthentication is in `beforeModel` and the API error is in the `model` hook. This is the only way I found to redirect if there is an authentication error.

File: frontend/app/ui/error/route.js (hunk 1 above)
Comment (fkm-adfinis) [reply frontend/app/ui/error/route.js]: Done

File: frontend/app/routes/-authenticated.js (hunk 2 above)
Comment (fkm-adfinis) [reply frontend/app/routes/-authenticated.js:21]: I added `this.session.invalidate()` to the if-clause. This way the next page-request will be caught by the `sesssion.requireAuthentication`.

**Comment by fkm-adfinis** [comment]
I need to be more careful with the CLI. I accidentally deleted the error template. I replaced it and also moved the breadcrumbs to the new controller.

File: frontend/app/ui/account/login/route.js (hunk 4 above)
Comment (anehx) [reply frontend/app/ui/account/login/route.js:9]: Aaah so this is basically the ex. unauthenticated route?

Comment (fkm-adfinis) [reply frontend/app/ui/account/login/route.js:9]: Yes

File: frontend/app/routes/-authenticated.js (hunk 2 above)
Comment (anehx) [reply frontend/app/routes/-authenticated.js:21]: If simple auth is correctly configured `this.session.invalidate()` should be enough, this triggers a redirect.. However my question still stands: why are you not using the application adapters handle response method like in [the example by ember simple auth](https://github.com/simplabs/ember-simple-auth/blob/74dd9cd2af45d791e0367d9671146eaaba2266f4/packages/ember-simple-auth/addon/mixins/data-adapter-mixin.js#L60-L94). This here you will only handle errors that happen in the model hook.

**Review by anehx — CHANGES_REQUESTED** [review]

File: frontend/app/routes/-authenticated.js (hunk 2 above)
Comment (fkm-adfinis) [reply frontend/app/routes/-authenticated.js:21]: I will have to check my configuration then.

Concerning the adapter. If I do the stuff from the example in my adapters `handleResponse` I get an empty error (without redirect). But if I get the redirect to work, that wouldn't be a problem.

Comment (fkm-adfinis) [reply frontend/app/routes/-authenticated.js:21]: I added the handleResponse code from simple-auth but I don't see a way to make the redirect happen automatically. I also updated to the latest version of simple-auth (before was a beta) but that didn't help either.

Do you have an idea, what I could have configured incorrectly? The addon doesn't seem to have a classic configuration (anymore) as we have with simple-auth-oidc.

Any help would be appreciated!

Comment (anehx) [reply frontend/app/routes/-authenticated.js:21]: The `rootURL` config option has to be correct. If you look at the [code here](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/addon/services/session.js#L204) it should redirect automatically after invalidation.

If the redirect works you shouldn't need the error handler in the authenticated route model hook.

Comment (anehx) [reply frontend/app/routes/-authenticated.js:21]: Are the handlers being registered, is `_setupHandlers` called?

**Review by anehx — APPROVED** [review]
